# Similarity based

Algorithm: 

Compute similarity using subsequence similarity: Hunt-Szymanski Algorithm

Compute clusters using kmemoids: PAM algorithm

Measure anomaly using dissimalirty to the memoid.


LCS implementation: https://www.geeksforgeeks.org/python-program-for-longest-common-subsequence/

KMemoids implementation: https://www.researchgate.net/publication/272351873_NumPy_SciPy_Recipes_for_Data_Science_k-Medoids_Clustering

In [1]:
from sklearn_extra.cluster import KMedoids
from sklearn.metrics import pairwise_distances
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

from Kmedoids import kMedoids
from helper_functions import pairwise_distance, nLCS
from score_distance import distance_k_neighbor, distance_clusters

In [19]:
def assign_to_cluster(X_test, M, metric):
    # Compute the similarity
    dist = pairwise_distance(X_test, metric, Y = M)

    assign = np.argmax(dist, axis = 1)
    
    return assign, np.max(dist, axis = -1)
    

In [3]:
def convert_str_data(X):
    return np.expand_dims(np.arange(X.shape[0]), axis = -1)

In [4]:
# Define some strings

a = "fasdjfksdafjsdklfj"
b = "erfgujergjiojiolergjikmv"
c = "aaaaaaaaa"
d = "thasjkhj"

In [5]:
# Example of computing the nLCS similarity
nLCS(b,b), nLCS(a,b)

(1.0, 0.24056261216234406)

In [6]:
X = np.array([a,b,c, d])

In [7]:
X_num = convert_str_data(X)

In [8]:
# The distance matrix is 1-similarity
D  = pairwise_distance(X, nLCS)

D = 1-D
D

array([[0.        , 0.75943739, 0.84286516, 0.58333333],
       [0.75943739, 0.        , 1.        , 0.85566243],
       [0.84286516, 1.        , 0.        , 0.88214887],
       [0.58333333, 0.85566243, 0.88214887, 0.        ]])

In [9]:
distance_k_neighbor(D, 2)

array([0.75943739, 0.85566243, 0.88214887, 0.85566243])

In [10]:
# Find the clusters and medoids using the k-medoids algorithm

n_clusters = 2
M, C = kMedoids(D, n_clusters)

M, C

(array([0, 3], dtype=int64),
 {0: array([0, 1, 2], dtype=int64), 1: array([3], dtype=int64)})

In [13]:
M.shape, test.shape

((2,), (2,))

In [20]:
test = np.array(["the", "help", "Hello"])
assign_to_cluster(test, X[M], nLCS)

(array([1, 1, 0], dtype=int64), array([0.40824829, 0.1767767 , 0.10540926]))

In [ ]:
type(None)

In [ ]:
# Compute the score given by the distance to the cluster medoid
distance_clusters(D, C, M )

In [ ]:
#compute the score given by the distance to the kth nearest neighbor

distance_k_neighbor(D, 2)